blog/urls.py
from django.urls import path
from . import views 

urlpatterns=[
    path('', views.index, name='index'),
    path('search/', views.search_function, name='search_url'),
    path('news/<slug:slug>/', views.post_detail, name='post_detail_url'),
    path('news/<slug:slug>/comment/', views.comment, name='comment'),
    path('categories/<slug:slug>/', views.category_detail, name='category_detail_url'),
    path('register/', views.register, name='register'),
] 

news_portal/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings  
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), #127.0.0.1:8000/admin
    path('',include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')), #127.0.0.1:8000/accounts
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  

blog/models.py
from django.db import models
from django.utils import timezone
# from .models import Post, Category
from django.shortcuts import reverse
from django.contrib.auth.models import User

class Category(models.Model):
    title = models.CharField("Sarlavha", max_length=255)
    slug = models.SlugField("Silka", unique=True)
    image = models.ImageField("Rasm", blank=True, null=True )

    class Meta:
        verbose_name = 'Kategoriya'
        verbose_name_plural = 'Kategoriyalar'

    def get_absolut_url(self):
        return reverse('category_detail_url', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField("Sarlavha", max_length=255)
    slug = models.SlugField("Silka", unique=True)
    image = models.ImageField("Rasm", blank=True, null=True )
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Kategoriya")
    content = models.TextField("Text")
    date = models.DateTimeField("Sana",default=timezone.now)
    publish = models.BooleanField("Taqdim etish", default=False) 

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Postlar'

    def get_absolut_url(self):
        return reverse('post_detail_url', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Avtor")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="Yangilik")
    text = models.TextField("Kommentariya")
    data = models.DateField("Sana", default=timezone.now)

    class Meta:
        verbose_name = "Kommentariya"
        verbose_name_plural = "Kommentariyalar"

   

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username = forms.CharField(label="Foydalanuvchi", required=True, widget=forms.TextInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    password1 = forms.CharField(label="Parol", required=True, widget=forms.PasswordInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    password2 = forms.CharField(label="Takror", required=True, widget=forms.PasswordInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    email = forms.CharField(label="Email", required=True, widget=forms.EmailInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    first_name = forms.CharField(label="Ism", required=True, widget=forms.TextInput(attrs={'class': 'form-control footer-input margin-b-20'}))
    last_name = forms.CharField(label="Familiya", required=True, widget=forms.TextInput(attrs={'class': 'form-control footer-input margin-b-20'}))


    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.last_name = self.cleaned_data["last_name"]
        user.first_name = self.cleaned_data["first_name"]

        if commit:
            user.save()
            return user()

blog/views.py
from django.shortcuts import render
from .models import Post
from django.db.models import Q 
from .models import Category
from .forms import RegisterForm


def index(request):
    posts = Post.objects.order_by('id')
    return render(request, 'blog/index.html', {'posts': posts})

def search_function(request):
    query = request.GET.get('search_input')
    posts = Post.objects.filter(Q(title__icontains = query))
    return render(request, 'blog/search.html', {'query': query, 'posts': posts})

def post_detail(request, slug):
    post = Post.objects.get(slug__exact = slug)
    return render(request, 'blog/post_detail.html', {'post': post})

def category_detail(request, slug):
    category = Category.objects.get(slug__exact = slug)
    return render(request, 'blog/category_detail.html', {'category': category})

def register(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('login')
        else:
            form = RegisterForm()    
        return render(request, 'blog/register.html', {'form': form})
    return redirect('index')

def comment(request, slug):
    post = Post.objects.get(slug__exact = slug)
    if request.method == "POST":
        post.comment_set.create(
            user = request.user,
            text = request.POST.get('text')
        )
        return redirect(reverse('post_datail_url', kwargs={'slug': post.slug}))
    return redirect(reverse('post_detail_url', kwargs={'slug': post.slug}))

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Bekorchilaaa</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active"  href="{% url 'index' %}">Asosiy</a>
              </li>
              {% if not user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Registratsiya</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Kirish</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Chiqish</a>
              </li>
              {% endif %}
              
            </ul>
            <form action="{% url 'search_url' %}" method="GET" class="d-flex">
              <input required name="search_input" class="form-control me-2" type="search" placeholder="Qidiruv" aria-label="Search">
              <button class="btn btn-outline-success" >Qidiruv</button>
            </form> 
          </div>
        </div>
      </nav>

    {% block content %}

    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
<script src="/static/bootstrap.min.js"></script>
  
</body>
</html>

blog/templates/blog/category_detail.html
{% extends 'base.html' %}

{% block title %}
{{post.title}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h3 class="text-center">{{post.title}}</h3>
            {% if category.image.url != null %}
                <img src="{{category.image.url}}" style="width: 100%;" alt="">
            {% endif %}
            <h3>{{category.title}}</h3>
            <hr>
            {% for post in category.post_set.all %}
            <div class="col-md-4">
              <div class="card">
                {% if post.image.url != null %}
                  <img style="height: 300px; object-fit: cover" src="{{post.image.url}}" class="card-img-top" alt="...">
                  {% endif %}
                  <div class="card-body">
                    <h5 class="card-title">{{post.title}}</h5>
                    <p class="card-text">{{post.content|slice:"0:100"}}</p>
                    <a href="{{post.category.get_absolut_url}}" class="btn btn-primary">{{post.category.title}}</a>
                  </div>
                  
                </div>
            </div>
          {% endfor %}   

        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block content %}
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
      <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"></li>
      <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"></li>
      <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img style='height: 500px; object-fit: cover;' src="https://wallpaperaccess.com/full/1125252.jpg" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img style='height: 500px; object-fit: cover;' src="https://i.pinimg.com/originals/82/5a/4a/825a4a94775dd4644c3699a5502912ba.jpg" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img style='height: 500px; object-fit: cover;' src="https://images2.alphacoders.com/955/955061.jpg" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </a>
  </div>
  <h1 class="text-center">Yangiliklar</h1>
  <hr>
  
  <section class="container-fluid">
      <div class="container">
          <div class="row">
            {% for post in posts %}
              <div class="col-md-4">
                <div class="card">
                  {% if post.image.url != null %}
                    <img style="height: 300px; object-fit: cover" src="{{post.image.url}}" class="card-img-top" alt="...">
                    {% endif %}
                    <div class="card-body">
                      <a href="{{post.get_absolut_url}}"><h5 class="card-title">{{post.title}}</h5></a>
                      <p class="card-text">{{post.content|slice:"0:100"}}</p>
                      <a href="{{post.category.get_absolut_url}}" class="btn btn-primary">{{post.category.title}}</a>
                    </div>
                    
                  </div>
              </div>
            {% endfor %}
          </div>
      </div>
  </section>
  <h2 class="text-center">Jahon yangiliklari</h2>
  <hr>
  <section class="container-fluid">
    <div class="container">
      <div class="row">
        <div class="col-md-2">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" class="card-link">Card link</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" class="card-link">Card link</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" class="card-link">Card link</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" class="card-link">Card link</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" class="card-link">Card link</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              <a href="#" class="card-link">Card link</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <br>
  <footer style="background-color: rgba(60, 255, 0, 0.603);">
    <h3 class="text-center">BlackPhoenix</h3>
  </footer>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{post.title}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h3 class="text-center">{{post.title}}</h3>
            {% if post.image.url != null %}
                <img src="{{post.image.url}}" style="width: 100%;" alt="">
            {% endif %}
            <p>{{post.content}}</p>
            <p class = "text-right">
                <i>{{post.date|date:"d F, Y"}}</i>
            </p>
            <hr>
            <p>
                <i>Kommentariyalar: {{post.comment_set.count}}</i>
            </p>
            <h3>Kommentariya qoldirish</h3>
            {% if user.is_authernticated %}
            <form action="{% url 'comment' post.slug %}" method="POST"></form>
                {% csrf_token %}
                <p>
                    <textarea name="" id="" cols="30" rows="10"class="form-control"></textarea>
                </p> 
                <p class="text-right"> 
                    <button class="btn btn-outline-primary"></button>
                
                </p>
            {% else %}
            <P>Kommentariya qoldirish uchun <a href="{% url 'register' %}">ro`yxatdan</a>  o`ting!!! <br> yoki tizimga <a href="{% url 'login' %}">kiring</a> </P>
            {% endif %}
            <hr>
            {% for comment in post.comment_set.all %}
            <div class="col-md-12">
                <h3>{{comment.user.username}}</h3>
                <p>{{comment.text}} </p>
                <p class="text-right">{{comment.date|timesince}} oldin</p>
            </div>
            {% endfor %}
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'base.html' %}

{% block title %}
Registratsiya
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <form action="{% url 'register' %}" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-success">Registratsiya</button>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/search.html
{% extends 'base.html' %}
{% block title %}
Qidiruv bo`yicha {{query}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                {% for post in posts %}
                <div class="col-md-4">
                    {% if post.image.url != null %}
                    <img src="{{post.image.url}}" alt="">
                    {% endif %}
                    <h3 class="text-center">{{post.title}}</h3>
                </div>
                {% empty %}
                <h2>Suralgan "{{query}}" bo`yicha hech narsa topilmadi" </h2>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>



{% endblock %}